### ISSUE TITLE
nothing happens when i press the buttons

### ISSUE THREAD

**Issue by Benneyz** [005Konz/Blooket-Cheats#1]
### Script

not sure

### Problem

yeah, idk why i got the bookmark in, and the blooket loaded up, but nothing happens when i use the bookmark.

### Method

Imported Bookmarklets.html

### Type

Obfuscated

**Comment by 005Konz** [comment]
Which cheats did you try

**Comment by Benneyz** [comment]
tried the tower defense ones, and global. also tried the gui

**Comment by 005Konz** [comment]
What browser do you use?

**Comment by Benneyz** [comment]
google

**Comment by 005Konz** [comment]
School device?

**Comment by Benneyz** [comment]
chromebook

**Comment by 005Konz** [comment]
Javascript might be blocked on your device, try typing `javascript:alert("Hello")` into your search bar and see if it says Hello

**Comment by Benneyz** [comment]
damn your totally right, darn

**Comment by Benneyz** [comment]
didnt work, definitely is blocked
