### ISSUE TITLE
SKID: <https://rustycheats75.sell.app/>

### ISSUE THREAD

**Issue by TheDarknessSurroundsYou** [005Konz/Blooket-Cheats#13]
### Skid

https://rustycheats75.sell.app/

### Stolen

main gui
they are charging real money for this.
![image](https://github.com/user-attachments/assets/3d76c451-6118-416b-9426-8e98ea786ce0)

**Comment by TheDarknessSurroundsYou** [comment]
also can I get unbanned from your discord? lol

**Comment by 005Konz** [comment]
If people are going to blindly buy a text file without at least googling for it, they deserved to get scammed.
And people really only get banned from the Discord server if they got their account hacked, change your password and send your username
