### ISSUE TITLE
BUG: flappy blook cheats

### ISSUE THREAD

**Issue by Githubman6996** [005Konz/Blooket-Cheats#2]
### Script

Flappy blook 

### Problem

They aren’t working 

### Method

Put 'javascript:(code)' in the url bar or a bookmark, Other (described in Extra Info section)

### Type

Normal, Minified

**Comment by S-PScripts** [comment]
javascript is probably blocked

**Comment by Githubman6996** [comment]
I’m on a home device

**Comment by 005Konz** [comment]
Just tested both the bookmarklets and in the GUIs and they're working fine, are you sure you ran it properly?

**Comment by Githubman6996** [comment]
I might’ve clicked the wrong gui because I have multiple in my bookmarks

**Comment by 005Konz** [comment]
Yes they are

**Comment by Githubman6996** [comment]
I was using the wrong gui I have multiple bookmarked guis  sorry
