### ISSUE TITLE
What happend to 05konz

### ISSUE THREAD

**Issue by Slaveyou** [005Konz/Blooket-Cheats#5]
### Script

IDK

### Problem

I saw the other konz but why is their now 2 zeroes instead of one?

### Method

Other (described in Extra Info section)

### Type

Normal

**Comment by DannyDan0167** [comment]
The original account was suspended and there was a gitlab. Konz was able to make another GitHub account under a different name which is 005konz. (Which is still her)

**Comment by Githubman6996** [comment]
![IMG_8193](https://github.com/005Konz/Blooket-Cheats/assets/144396091/e1a66b9d-2a9b-4638-b589-48a25f6f33b0)

**Comment by Githubman6996** [comment]
There was also Konz 2nd account but it only lasted a few hours

**Comment by ShorterCat194** [comment]
Why Does 05Konz now Have 2 0's??

**Comment by Shortercat194** [comment]
Hi @ghost,
Read Above

**Comment by otmfyourandomize** [comment]
005konz is her new account for github. 05konz was main. Which got suspended ofc. She has gitlab to, she made that after the suspension.

**Comment by CryptoDude3** [comment]
how is this a bug?

**Comment by Slaveyou** [comment]
@CryptoDude3 Its not lol
