### ISSUE TITLE
bypassed usernames

### ISSUE THREAD

**Issue by bonmarkzz** [005Konz/Blooket-Cheats#7]
### Gamemode

Global

### Function

the gui can have an element that whenever you type into the box it filters out the username in which you can type in the bypassed username.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 005Konz** [comment]
Can't get around server-side checks

**Comment by CryptoDude3** [comment]
> Can't get around server-side checks

u can by just putting invisible chars in between the name
I also think he means ingame username not login username

**Comment by Githubman6996** [comment]
(async () => {
const reactHandler = (e=>Object.values(document.querySelector("#app>div>div"))[1].children[0]._owner.stateNode);
let i = document.createElement('iframe');
document.body.append(i);
let prompt = i.contentWindow.prompt.bind(window);
let alert = i.contentWindow.alert.bind(window);
i.remove();
async function genToken(name){
const res = await fetch("https://fb.blooket.com/c/firebase/join", {
    body: JSON.stringify({ id:reactHandler().props.client.hostId, name }),
    headers: {
      "Content-Type": "application/json"
    },
    method: "PUT",
    credentials: "include"
  }).then(e=>e.json());
if(!res.success){alert("Error: " + res.msg);return;}
return res.fbToken;
}
const newname = prompt("Enter your new name here:");
const oldname = reactHandler().props.client.name;
reactHandler().props.client.name = newname;
const olddata = await reactHandler().props.liveGameController.getDatabaseVal(`c/${oldname}`);
await reactHandler().props.liveGameController.removeVal(`c/${oldname}`);
const token = await genToken(newname);
if(!token){return;}
await reactHandler().props.liveGameController._liveApp.auth().signInWithCustomToken(token);
reactHandler().props.liveGameController._liveApp.auth().onAuthStateChanged(e=>{if(e.uid.split(":")[1] === newname){reactHandler().props.liveGameController.setVal({path:`c/${newname}`,val:olddata});}})
reactHandler().render();
})();


@005Konz
