### ISSUE TITLE
Someone's Skidding Konz

### ISSUE THREAD

**Issue by HackTheGame194** [005Konz/Blooket-Cheats#8]
### Skid

https://github.com/minesraft4/blooket-gui/issues/39
Scroll Down To Bottom

### Stolen

@shorterCat194 Stole All  Your Codes

NOTE: YOU ARE NOT ALLOWED TO STEAL ANYONES SCRIPTS UNLESS EXPLAINED IN 'README'

**Comment by CryptoDude3** [comment]
if you're so mad about it then why are you supporting them:
[](https://github.com/HackTheGame194/Every-Blooket-Hack/tree/Cheats%40Main)

**Comment by CanYouHack194** [comment]
Hi @HackTheGame194 (@ghost),

You **Were** Supporting Them But In Your Message You Said NOT To Support Them As You Said @CryptoDude3 Was Being Illegi But He **WASNT *
